#include <stddef.h> //size_t
#include "libft.h"

/* MANDATORY - Libc */
void	check_ft_isalpha(void);
void	check_ft_isalpha_2(int low, int high);
int		util_ft_check_isalpha(int c);
void	check_ft_isdigit(void);
void	check_ft_isdigit_2(int low, int high);
int		util_ft_check_isdigit(int c);
void	check_ft_isalnum(void);
void	check_ft_isalnum_2(int low, int high);
int		util_ft_check_isalnum(int c);
void	check_ft_isascii(void);
void	check_ft_isascii_2(int low, int high);
void	check_ft_isprint(void);
void	check_ft_isprint_2(int low, int high);
int		util_ft_check_isprint(int c);
void	check_ft_strlen(void);
void	check_ft_strlen_2(const char *s);
void	check_ft_memset(void);
void	check_ft_memset_2(char *b, int c, size_t len);
void	check_ft_bzero(void);
void	check_ft_bzero_2(char *b, size_t len);
void	check_ft_memcpy(void);
void	check_ft_memcpy_2(char *dst, char *src, size_t n);
void	check_ft_memmove(void);
void	check_ft_memmove_2(void *dest, const void *src, size_t n);
void	check_ft_memmove_3(void *dest, int pos, size_t n);
void	check_ft_strlcpy(void);
void	check_ft_strlcpy_2(char *dst, const char *src, size_t dstsize);
void	check_ft_strlcat(void);
void	check_ft_strlcat_2(char *dst, const char *src, size_t dstsize);
void	check_ft_toupper(void);
void	check_ft_toupper_2(int low, int high);
int		util_ft_check_toupper(int c);
void	check_ft_tolower(void);
void	check_ft_tolower_2(int low, int high);
int		util_ft_check_tolower(int c);
void	check_ft_strchr_2(const char *s, int c);
void	check_ft_strchr(void);
void	check_ft_strrchr(void);
void	check_ft_strrchr_2(const char *s, int c);
void	check_ft_strncmp(void);
void	check_ft_strncmp_2(const char *s1, const char *s2, size_t n);
void	check_ft_memchr(void);
void	check_ft_memchr_2(const char *s, int c, size_t n);
void	check_ft_memcmp(void);
void	check_ft_memcmp_2(const char *s1, const char *s2, size_t n);
int		utils_ft_memcmp(const char *s1, const char *s2, size_t n);
void	check_ft_strnstr(void);
void	check_ft_strnstr_2(const char *haystack, const char *needle, size_t len);
void	check_ft_atoi(void);
void	check_ft_atoi_2(const char *str);
void	check_ft_atoi_3(const char *str);
void	check_ft_calloc(void);
void	check_ft_calloc_2(size_t count, size_t size);
void	check_ft_strdup(void);
void	check_ft_strdup_2(const char *s);
/* MANDATORY - Additional */
void	check_ft_substr(void);
void	check_ft_substr_2(char const *s, unsigned int start, size_t len, char const *check);
void	check_ft_substr_prot(void);
void	check_ft_strjoin(void);
void	check_ft_strjoin_2(char const *s1, char const *s2, char const *check);
void	check_ft_strjoin_prot(void);
void	check_ft_strtrim(void);
void 	check_ft_strtrim_2(const char *s1, char const *set, char const *check);
void	check_ft_strtrim_prot(void);
void	check_ft_split(void);
void	check_ft_split_2(char const *s, char c);
void	check_ft_split_prot(void);
void	check_ft_itoa(void);
void	check_ft_itoa_2(int n, char *check);
void	check_ft_strmapi(void);
void	check_ft_strmapi_2(const char *s, const char *check);
void	check_ft_strmapi_prot(void);
void	check_ft_striteri(void);
void	check_ft_striteri_2(char *s, char *check, void (*f)(unsigned int, char*));
void	check_ft_striteri_prot(void);
void	check_ft_putchar_fd(void);
void	check_ft_putchar_fd_2(int low, int high);
int		check_ft_putchar_fd_3(char c);
void	check_ft_putstr_fd(void);
void	check_ft_putstr_fd_2(char *s);
void	check_ft_putstr_fd_prot(void);
void	check_ft_putendl_fd(void);
void	check_ft_putendl_fd_2(char *s);
void	check_ft_putendl_fd_prot(void);
void	check_ft_putnbr_fd(void);
void	check_ft_putnbr_fd_2(int n, char *check);
/* BONUS */
void	check_ft_lstnew(void);
void	check_ft_lstnew_2(char *str);
void	check_ft_lstnew_3(void);
void	check_ft_lstadd_front(void);
void	check_ft_lstadd_front_2(t_list *lst);
void	check_ft_lstadd_front_3(t_list *lst);
void	check_ft_lstsize(void);
void	check_ft_lstsize_2(int count);
void	check_ft_lstlast(void);
void	check_ft_lstlast_2(int count);
void	check_ft_lstadd_back(void);
void	check_ft_lstadd_back_2(int count);
void	check_ft_lstdelone(void);
void	check_ft_lstdelone_2(void);
void	check_ft_lstclear(void);
void	check_ft_lstclear_2(int count);
void	check_ft_lstiter(void);
void	check_ft_lstiter_2(int count);
int		check_ft_lstiter_3(t_list *lst, t_list *check);
void	check_ft_lstiter_prot(void);
void	check_ft_lstmap(void);
void	check_ft_lstmap_2(int count);
int 	check_ft_lstmap_3(t_list *lst, t_list *newlst, t_list *check);
void	check_ft_lstmap_prot(void);
